#!/bin/bash

# The calculator script
function add()
{
	ans=$(($first+$second))
}
function subt()
{
	ans=$(($first-$second))
}

function menu1()
{
	clear
	echo "C) calculation"
	echo "X) Exit"
}

function menu2()
{
	clear
	echo "Please enter an integer number or X to exit"
}

function menu3()
{
	clear
	echo "+) Add"
	echo "-) Subtract"
	echo "X) Exit"
}

# take parameters
if [ $# == 2 ]
then
	first=$1
	second=$2
	add
	echo "The sum of $first plus $second is $ans"
	subt
	echo "The subtraction of $first minus $second is $ans"
fi

if [ $# == 3 ]
then
	first=$1
  second=$3
  if  [ $2 == "+" ]
	then
		add
	  echo "The sum of $first plus $second is $ans"
	elif [ $2 == "-" ]
	then
		subt
		echo "The subtraction of $first minus $second is $ans"
	fi
fi

if [ $# == 0 ]
then

	while true
	do
		menu1
		read choice

		if [ $choice == "C" ] || [ $choice == "c" ]
		then
	     menu2
			 read first
	     if [ $first == "X" ] || [ $first == "x" ]
			 then
				 exit 0
			 fi
			 menu3
			 read cal
			 if [ $cal == "X" ] || [ $cal == "x" ]
			 then
				 exit 0
			 elif [ $cal != "+" ] && [ $cal != "-" ]
			 then
				 echo "Must enter + or - or EXIT by X"
				 exit 0
			 fi
			 menu2
			 read second
			 if [ $second == "X" ] || [ $second == "x" ]
			 then
				 exit 0
			 fi

			 #calculation
			 if  [ $cal == "+" ]
			 then
				 add
				 echo "The sum of $first plus $second is $ans"
			 elif [ $cal == "-" ]
			 then
				 subt
				 echo "The subtraction of $first minus $second is $ans"
			 fi
	  elif [ $choice == "X" ] || [ $choice == "x" ]
		then
		   exit 0
		fi

		sleep 3
  done
fi
